@baseGateway = http://localhost:4000


### Auth Register
POST {{baseGateway}}/auth/register
content-type: application/json

{
    "email": "anna1.doe@example.com",
    "displayName": "anna Doe",
    "password": "Password123!"
}